from . import cmd_start
from . import cmd_menu
from . import cmd_support
from . import cmd_support_call
from . import cmd_transport
from . import cmd_news
from . import cmd_security
from . import cmd_advertising
from . import cmd_poshta
from . import cmd_horoscope
from . import cmd_vote_mute
from . import cmd_medicine
from . import cmd_autostrah
from . import cmd_internet
from . import cmd_business_center_porydok
from . import cmd_passport_table
from . import other
